#' 2-dimensional plot of the covariance overlap between continguous mutual information matrices, defined in the input trajectory.
#' 
#' This function generates a 2d plot of the diagonal of the smoothed covariance overlap matrix, generated by matrix_smooth().
#' The function generates a plot.
#'  
#' 
#'
#' @param overlap.matrix.s Smoothed matrix of covariance overlaps, computed using matrix_smooth().
#' @param t.traj Length of the MD simulation, in nanoseconds.
#' @return A plot 
#' @export



sectors_2dplot = function(overlap.matrix.s, t.traj){

	# take the diagonal of the covariance overlap matrix
	sector.v = diag(overlap.matrix.s$z)

	# determine a vector defining the trajectory time-sequence
	times = seq(from = 0, to = t.traj, length.out = length(sector.v))

	# combine time and covariance overlap values into a single dataframe
	dat = cbind(times, sector.v)

	# generate the plot to a pdf file
	par(mar = c(5,5,2,2))

	plot(dat,
		pch = 1,
		cex = 2,
		xlab = 'Time (ns)',
		ylab = expression(paste(Omega['A;B'])),
		panel.first = grid(lwd = 2),
		cex.axis = 2,
		cex.lab = 2,
		type = 'o')


}
