#' Image plot of the covariance overlap between all mutual information matrices defined in the input trajectory.
#' 
#' This function generates and image plot of the smoothed covariance overlap matrix generated by matrix_smooth().
#' The function saves an image plot as *.pdf in the working directory.
#'  
#' 
#'
#' @param overlap.matrix.s Smoothed matrix of covariance overlaps, computed using matrix_smooth().
#' @param t.traj Length of the MD simulation, in nanoseconds.
#' @return An image plot in *.pdf
#' @export



sectors_3dplot = function(overlap.matrix.s, t.traj){

	# determine a vector defining the trajectory time-sequence
	times = seq(from = 0, to = t.traj, length.out = ncol(overlap.matrix.s))

	# generate the image plot to a pdf file
	pdf('sector_3dplot.pdf')
	
	par(mar=c(5,5,2,2))

	fields::image.plot(times, times, overlap.matrix.s$z,
	        legend.cex=2,
	        cex=2,
	        xlab="Time (ns)",
	        ylab="Time (ns)")

	dev.off()

}